repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-case-conflict
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: data
    - id: trailing-whitespace
      exclude: data
    - id: mixed-line-ending
    - id: check-ast
    - id: debug-statements
    - id: detect-private-key
    - id: check-added-large-files
      args: [--maxkb=50000]
    - id: check-merge-conflict
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: no-commit-to-branch
      args: [--branch, prod, --branch, staging]

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    - id: black
      exclude: ^ipynb

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [src, -v, -i, --fail-under=80]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
